var searchData=
[
  ['setup_0',['Repository Setup',['../group__CourseGuide.html#autotoc_md3',1,'']]],
  ['setup_20—_20students_20strong_20and_20strong_20instructors_1',['2.0 Initial Setup — Students &lt;strong&gt;and&lt;/strong&gt; Instructors',['../group__CG__GitHubWorkflow.html#autotoc_md66',1,'']]],
  ['setup_20br_2',['Repository Setup  &lt;br&gt;',['../group__CG__RepositorySetup.html',1,'']]],
  ['should_20enable_20github_20pages_3',['2.4 Why Students Should Enable GitHub Pages',['../group__CG__GitHubWorkflow.html#autotoc_md76',1,'']]],
  ['src_20lectureexample_5fprivateapi_20cpp_20tt_4',['Implementation — &lt;tt&gt;course/src/LectureExample_privateAPI.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md122',1,'']]],
  ['src_20studentexample_5fprivateapi_20cpp_20tt_5',['Implementation — &lt;tt&gt;student/src/StudentExample_privateAPI.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md127',1,'']]],
  ['strong_20and_20strong_20instructors_6',['2.0 Initial Setup — Students &lt;strong&gt;and&lt;/strong&gt; Instructors',['../group__CG__GitHubWorkflow.html#autotoc_md66',1,'']]],
  ['structure_7',['structure',['../group__CG__LocalWorkflow.html#autotoc_md62',1,'1.3 Course Guide Structure'],['../group__CourseGuide.html#autotoc_md4',1,'Directory Structure']]],
  ['structure_20br_8',['Directory Structure  &lt;br&gt;',['../group__CG__DirectoryStructure.html',1,'']]],
  ['student_20boilerplate_20code_20tt_20studentlib_20tt_9',['9.2 Student Boilerplate Code (&lt;tt&gt;StudentLib&lt;/tt&gt;)',['../group__CG__Lesson0.html#autotoc_md125',1,'']]],
  ['student_20code_10',['9.3 How Instructor Tests Validate Student Code',['../group__CG__Lesson0.html#autotoc_md130',1,'']]],
  ['student_20code_20tt_20student_20tt_11',['3.0 Student Code (&lt;tt&gt;student/&lt;/tt&gt;)',['../group__CG__DirectoryStructure.html#autotoc_md23',1,'']]],
  ['student_20examples_20studentexample_5ftarget_20cpp_20tt_12',['Example — &lt;tt&gt;student/examples/StudentExample_target.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md128',1,'']]],
  ['student_20fork_20documentation_3a_13',['Student fork documentation:',['../group__CG__GitHubWorkflow.html#autotoc_md73',1,'']]],
  ['student_20include_20studentexample_5fpublicapi_20hpp_20tt_14',['Public header — &lt;tt&gt;student/include/StudentExample_publicAPI.hpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md126',1,'']]],
  ['student_20src_20studentexample_5fprivateapi_20cpp_20tt_15',['Implementation — &lt;tt&gt;student/src/StudentExample_privateAPI.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md127',1,'']]],
  ['student_20tt_16',['3.0 Student Code (&lt;tt&gt;student/&lt;/tt&gt;)',['../group__CG__DirectoryStructure.html#autotoc_md23',1,'']]],
  ['student_20workflow_17',['4.0 Student Workflow',['../group__CG__GitHubWorkflow.html#autotoc_md84',1,'']]],
  ['studentexample_5fdocs_18',['StudentExample_docs',['../md_student_2docs_2StudentExample__docs.html',1,'']]],
  ['studentexample_5fprivateapi_20cpp_20tt_19',['Implementation — &lt;tt&gt;student/src/StudentExample_privateAPI.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md127',1,'']]],
  ['studentexample_5fpublicapi_20hpp_20tt_20',['Public header — &lt;tt&gt;student/include/StudentExample_publicAPI.hpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md126',1,'']]],
  ['studentexample_5ftarget_20cpp_20tt_21',['Example — &lt;tt&gt;student/examples/StudentExample_target.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md128',1,'']]],
  ['studentlib_22',['StudentLib',['../namespaceStudentLib.html',1,'']]],
  ['studentlib_20tt_23',['studentlib tt',['../group__CG__Lesson0.html#autotoc_md110',1,'6.2 &lt;tt&gt;StudentLib&lt;/tt&gt;'],['../group__CG__Lesson0.html#autotoc_md125',1,'9.2 Student Boilerplate Code (&lt;tt&gt;StudentLib&lt;/tt&gt;)']]],
  ['students_24',['1.0 Creating Your Fork (Required for Students)',['../group__CG__RepositorySetup.html#autotoc_md8',1,'']]],
  ['students_20instructors_25',['2.2 Enabling GitHub Pages (Students &amp; Instructors)',['../group__CG__GitHubWorkflow.html#autotoc_md70',1,'']]],
  ['students_20should_20enable_20github_20pages_26',['2.4 Why Students Should Enable GitHub Pages',['../group__CG__GitHubWorkflow.html#autotoc_md76',1,'']]],
  ['students_20strong_20and_20strong_20instructors_27',['2.0 Initial Setup — Students &lt;strong&gt;and&lt;/strong&gt; Instructors',['../group__CG__GitHubWorkflow.html#autotoc_md66',1,'']]],
  ['summary_28',['6.0 Summary',['../group__CG__GitHubWorkflow.html#autotoc_md88',1,'']]],
  ['summary_20—_20what_20lesson_200_20teaches_29',['10.0 Summary — What Lesson 0 Teaches',['../group__CG__Lesson0.html#autotoc_md132',1,'']]]
];
