var searchData=
[
  ['targets_0',['targets',['../group__CG__LocalWorkflow.html#autotoc_md30',1,'1.1 Build All Targets'],['../group__CG__DirectoryStructure.html#autotoc_md27',1,'5.0 Libraries and Targets']]],
  ['targets_20vs_20unit_20tests_1',['5.0 Example Targets vs. Unit Tests',['../group__CG__Lesson0.html#autotoc_md104',1,'']]],
  ['teaches_2',['10.0 Summary — What Lesson 0 Teaches',['../group__CG__Lesson0.html#autotoc_md132',1,'']]],
  ['template_3',['template',['../group__CG__Lesson0.html#autotoc_md90',1,'1.0 Purpose of the Template'],['../group__CG__Lesson0.html#autotoc_md117',1,'8.0 Why We Use This Template'],['../index.html',1,'cpp-course-template']]],
  ['test_20discovery_4',['1.0 Test Discovery',['../group__CG__LocalWorkflow.html#autotoc_md36',1,'']]],
  ['test_20files_5',['3.3 &lt;tt&gt;.cc&lt;/tt&gt; (Unit Test Files)',['../group__CG__Lesson0.html#autotoc_md97',1,'']]],
  ['testing_6',['Coverage Testing',['../group__CG__LocalWorkflow.html',1,'']]],
  ['tests_7',['tests',['../group__CG__LocalWorkflow.html#autotoc_md38',1,'1.1 Running All Tests'],['../group__CG__LocalWorkflow.html#autotoc_md52',1,'1.4 Excluding Examples and Tests'],['../group__CG__Lesson0.html#autotoc_md104',1,'5.0 Example Targets vs. Unit Tests'],['../group__CG__LocalWorkflow.html',1,'Running Unit Tests']]],
  ['tests_20generate_20coverage_20data_8',['1.2 Running Tests (Generate Coverage Data)',['../group__CG__LocalWorkflow.html#autotoc_md48',1,'']]],
  ['tests_20link_20to_20the_20libraries_9',['1.2 How Tests Link to the Libraries',['../group__CG__LocalWorkflow.html#autotoc_md40',1,'']]],
  ['tests_20tt_20_5funittests_20cc_20tt_10',['5.2 Unit Tests (&lt;tt&gt;*_unitTests.cc&lt;/tt&gt;)',['../group__CG__Lesson0.html#autotoc_md106',1,'']]],
  ['tests_20validate_20student_20code_11',['9.3 How Instructor Tests Validate Student Code',['../group__CG__Lesson0.html#autotoc_md130',1,'']]],
  ['the_20build_20directory_12',['1.0 Configure the Build Directory',['../group__CG__LocalWorkflow.html#autotoc_md28',1,'']]],
  ['the_20ci_20workflows_13',['3.0 Understanding the CI Workflows',['../group__CG__GitHubWorkflow.html#autotoc_md78',1,'']]],
  ['the_20github_20workflow_14',['1.0 Purpose of the GitHub Workflow',['../group__CG__GitHubWorkflow.html#autotoc_md64',1,'']]],
  ['the_20libraries_15',['1.2 How Tests Link to the Libraries',['../group__CG__LocalWorkflow.html#autotoc_md40',1,'']]],
  ['the_20project_16',['Building the Project',['../group__CG__LocalWorkflow.html',1,'']]],
  ['the_20repository_20is_20organized_20this_20way_17',['2.0 Why the Repository Is Organized This Way',['../group__CG__Lesson0.html#autotoc_md92',1,'']]],
  ['the_20template_18',['1.0 Purpose of the Template',['../group__CG__Lesson0.html#autotoc_md90',1,'']]],
  ['this_20template_19',['8.0 Why We Use This Template',['../group__CG__Lesson0.html#autotoc_md117',1,'']]],
  ['this_20way_20',['this way',['../group__CG__Lesson0.html#autotoc_md92',1,'2.0 Why the Repository Is Organized This Way'],['../group__CG__Lesson0.html#autotoc_md94',1,'3.0 Why File Extensions Are Chosen This Way']]],
  ['to_20the_20libraries_21',['1.2 How Tests Link to the Libraries',['../group__CG__LocalWorkflow.html#autotoc_md40',1,'']]],
  ['toolchain_22',['2.0 Required Toolchain',['../group__CG__RepositorySetup.html#autotoc_md10',1,'']]],
  ['top_20level_20layout_23',['1.0 Top-Level Layout',['../group__CG__DirectoryStructure.html#autotoc_md19',1,'']]],
  ['topics_20doxygen_20groups_24',['Course Guide Topics (Doxygen Groups)',['../group__CourseGuide.html#autotoc_md2',1,'']]],
  ['tt_20_5ftarget_20cpp_20tt_25',['5.1 Example Executables (&lt;tt&gt;*_target.cpp&lt;/tt&gt;)',['../group__CG__Lesson0.html#autotoc_md105',1,'']]],
  ['tt_20_5funittests_20cc_20tt_26',['5.2 Unit Tests (&lt;tt&gt;*_unitTests.cc&lt;/tt&gt;)',['../group__CG__Lesson0.html#autotoc_md106',1,'']]],
  ['tt_20cc_20tt_20unit_20test_20files_27',['3.3 &lt;tt&gt;.cc&lt;/tt&gt; (Unit Test Files)',['../group__CG__Lesson0.html#autotoc_md97',1,'']]],
  ['tt_20ci_20yml_20tt_20—_20main_20ci_20pipeline_28',['3.1 &lt;tt&gt;ci.yml&lt;/tt&gt; — Main CI Pipeline',['../group__CG__GitHubWorkflow.html#autotoc_md80',1,'']]],
  ['tt_20course_20examples_20lectureexample_5ftarget_20cpp_20tt_29',['Example — &lt;tt&gt;course/examples/LectureExample_target.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md123',1,'']]],
  ['tt_20course_20include_20lectureexample_5fpublicapi_20hpp_20tt_30',['Public header — &lt;tt&gt;course/include/LectureExample_publicAPI.hpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md121',1,'']]],
  ['tt_20course_20src_20lectureexample_5fprivateapi_20cpp_20tt_31',['Implementation — &lt;tt&gt;course/src/LectureExample_privateAPI.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md122',1,'']]],
  ['tt_20course_20tt_32',['2.0 Instructor Code (&lt;tt&gt;course/&lt;/tt&gt;)',['../group__CG__DirectoryStructure.html#autotoc_md21',1,'']]],
  ['tt_20courselib_20tt_33',['tt courselib tt',['../group__CG__Lesson0.html#autotoc_md109',1,'6.1 &lt;tt&gt;CourseLib&lt;/tt&gt;'],['../group__CG__Lesson0.html#autotoc_md120',1,'9.1 Instructor Boilerplate Code (&lt;tt&gt;CourseLib&lt;/tt&gt;)']]],
  ['tt_20cpp_20tt_20implementation_20files_34',['3.2 &lt;tt&gt;.cpp&lt;/tt&gt; (Implementation Files)',['../group__CG__Lesson0.html#autotoc_md96',1,'']]],
  ['tt_20docs_20tt_35',['4.0 Documentation (&lt;tt&gt;docs/&lt;/tt&gt;)',['../group__CG__DirectoryStructure.html#autotoc_md25',1,'']]],
  ['tt_20docs_20yml_20tt_20—_20documentation_20deployment_36',['3.2 &lt;tt&gt;docs.yml&lt;/tt&gt; — Documentation Deployment',['../group__CG__GitHubWorkflow.html#autotoc_md82',1,'']]],
  ['tt_20dox_20tt_20documentation_20pages_37',['3.4 &lt;tt&gt;.dox&lt;/tt&gt; (Documentation Pages)',['../group__CG__Lesson0.html#autotoc_md98',1,'']]],
  ['tt_20dox_20tt_20pages_20you_20document_3a_38',['In &lt;tt&gt;.dox&lt;/tt&gt; pages you document:',['../group__CG__Lesson0.html#autotoc_md115',1,'']]],
  ['tt_20hpp_20tt_20header_20files_39',['3.1 &lt;tt&gt;.hpp&lt;/tt&gt; (Header Files)',['../group__CG__Lesson0.html#autotoc_md95',1,'']]],
  ['tt_20include_20…_5fpublicapi_20hpp_20tt_20you_20document_3a_40',['In &lt;tt&gt;include/…_publicAPI.hpp&lt;/tt&gt; you document:',['../group__CG__Lesson0.html#autotoc_md114',1,'']]],
  ['tt_20student_20examples_20studentexample_5ftarget_20cpp_20tt_41',['Example — &lt;tt&gt;student/examples/StudentExample_target.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md128',1,'']]],
  ['tt_20student_20include_20studentexample_5fpublicapi_20hpp_20tt_42',['Public header — &lt;tt&gt;student/include/StudentExample_publicAPI.hpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md126',1,'']]],
  ['tt_20student_20src_20studentexample_5fprivateapi_20cpp_20tt_43',['Implementation — &lt;tt&gt;student/src/StudentExample_privateAPI.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md127',1,'']]],
  ['tt_20student_20tt_44',['3.0 Student Code (&lt;tt&gt;student/&lt;/tt&gt;)',['../group__CG__DirectoryStructure.html#autotoc_md23',1,'']]],
  ['tt_20studentlib_20tt_45',['tt studentlib tt',['../group__CG__Lesson0.html#autotoc_md110',1,'6.2 &lt;tt&gt;StudentLib&lt;/tt&gt;'],['../group__CG__Lesson0.html#autotoc_md125',1,'9.2 Student Boilerplate Code (&lt;tt&gt;StudentLib&lt;/tt&gt;)']]]
];
