var searchData=
[
  ['c_20course_20template_20—_20documentation_20portal_0',['C++ Course Template — Documentation Portal',['../index.html',1,'']]],
  ['cc_20tt_1',['5.2 Unit Tests (&lt;tt&gt;*_unitTests.cc&lt;/tt&gt;)',['../group__CG__Lesson0.html#autotoc_md106',1,'']]],
  ['cc_20tt_20unit_20test_20files_2',['3.3 &lt;tt&gt;.cc&lt;/tt&gt; (Unit Test Files)',['../group__CG__Lesson0.html#autotoc_md97',1,'']]],
  ['chosen_20this_20way_3',['3.0 Why File Extensions Are Chosen This Way',['../group__CG__Lesson0.html#autotoc_md94',1,'']]],
  ['ci_20pipeline_4',['3.1 &lt;tt&gt;ci.yml&lt;/tt&gt; — Main CI Pipeline',['../group__CG__GitHubWorkflow.html#autotoc_md80',1,'']]],
  ['ci_20workflows_5',['3.0 Understanding the CI Workflows',['../group__CG__GitHubWorkflow.html#autotoc_md78',1,'']]],
  ['ci_20yml_20tt_20—_20main_20ci_20pipeline_6',['3.1 &lt;tt&gt;ci.yml&lt;/tt&gt; — Main CI Pipeline',['../group__CG__GitHubWorkflow.html#autotoc_md80',1,'']]],
  ['cmake_20builds_20everything_7',['6.0 How CMake Builds Everything',['../group__CG__Lesson0.html#autotoc_md108',1,'']]],
  ['code_8',['9.3 How Instructor Tests Validate Student Code',['../group__CG__Lesson0.html#autotoc_md130',1,'']]],
  ['code_20tt_20course_20tt_9',['2.0 Instructor Code (&lt;tt&gt;course/&lt;/tt&gt;)',['../group__CG__DirectoryStructure.html#autotoc_md21',1,'']]],
  ['code_20tt_20courselib_20tt_10',['9.1 Instructor Boilerplate Code (&lt;tt&gt;CourseLib&lt;/tt&gt;)',['../group__CG__Lesson0.html#autotoc_md120',1,'']]],
  ['code_20tt_20student_20tt_11',['3.0 Student Code (&lt;tt&gt;student/&lt;/tt&gt;)',['../group__CG__DirectoryStructure.html#autotoc_md23',1,'']]],
  ['code_20tt_20studentlib_20tt_12',['9.2 Student Boilerplate Code (&lt;tt&gt;StudentLib&lt;/tt&gt;)',['../group__CG__Lesson0.html#autotoc_md125',1,'']]],
  ['code_20walkthrough_13',['9.0 Boilerplate Code Walkthrough',['../group__CG__Lesson0.html#autotoc_md119',1,'']]],
  ['comments_14',['1.2 Writing Doxygen Comments',['../group__CG__LocalWorkflow.html#autotoc_md60',1,'']]],
  ['commit_20only_20for_20manual_20repositories_15',['2.1 Initial Commit (Only for Manual Repositories)',['../group__CG__GitHubWorkflow.html#autotoc_md68',1,'']]],
  ['configuration_16',['configuration',['../group__CG__LocalWorkflow.html#autotoc_md56',1,'1.0 Configuration'],['../group__CG__RepositorySetup.html#autotoc_md14',1,'4.0 First Local Configuration']]],
  ['configure_20the_20build_20directory_17',['1.0 Configure the Build Directory',['../group__CG__LocalWorkflow.html#autotoc_md28',1,'']]],
  ['course_20examples_20lectureexample_5ftarget_20cpp_20tt_18',['Example — &lt;tt&gt;course/examples/LectureExample_target.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md123',1,'']]],
  ['course_20guide_20overview_19',['Course Guide Overview',['../group__CourseGuide.html#autotoc_md0',1,'']]],
  ['course_20guide_20structure_20',['1.3 Course Guide Structure',['../group__CG__LocalWorkflow.html#autotoc_md62',1,'']]],
  ['course_20guide_20topics_20doxygen_20groups_21',['Course Guide Topics (Doxygen Groups)',['../group__CourseGuide.html#autotoc_md2',1,'']]],
  ['course_20include_20lectureexample_5fpublicapi_20hpp_20tt_22',['Public header — &lt;tt&gt;course/include/LectureExample_publicAPI.hpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md121',1,'']]],
  ['course_20src_20lectureexample_5fprivateapi_20cpp_20tt_23',['Implementation — &lt;tt&gt;course/src/LectureExample_privateAPI.cpp&lt;/tt&gt;',['../group__CG__Lesson0.html#autotoc_md122',1,'']]],
  ['course_20template_20—_20documentation_20portal_24',['C++ Course Template — Documentation Portal',['../index.html',1,'']]],
  ['course_20tt_25',['2.0 Instructor Code (&lt;tt&gt;course/&lt;/tt&gt;)',['../group__CG__DirectoryStructure.html#autotoc_md21',1,'']]],
  ['courseguide_26',['CourseGuide',['../group__CourseGuide.html',1,'']]],
  ['courselib_20tt_27',['courselib tt',['../group__CG__Lesson0.html#autotoc_md109',1,'6.1 &lt;tt&gt;CourseLib&lt;/tt&gt;'],['../group__CG__Lesson0.html#autotoc_md120',1,'9.1 Instructor Boilerplate Code (&lt;tt&gt;CourseLib&lt;/tt&gt;)']]],
  ['coverage_20data_28',['1.2 Running Tests (Generate Coverage Data)',['../group__CG__LocalWorkflow.html#autotoc_md48',1,'']]],
  ['coverage_20flags_29',['1.1 Enabling Coverage Flags',['../group__CG__LocalWorkflow.html#autotoc_md46',1,'']]],
  ['coverage_20report_30',['coverage report',['../group__CG__LocalWorkflow.html#autotoc_md50',1,'1.3 Basic Coverage Report'],['../group__CG__LocalWorkflow.html#autotoc_md54',1,'1.5 HTML Coverage Report']]],
  ['coverage_20testing_31',['Coverage Testing',['../group__CG__LocalWorkflow.html',1,'']]],
  ['cpp_20tt_32',['cpp tt',['../group__CG__Lesson0.html#autotoc_md105',1,'5.1 Example Executables (&lt;tt&gt;*_target.cpp&lt;/tt&gt;)'],['../group__CG__Lesson0.html#autotoc_md123',1,'Example — &lt;tt&gt;course/examples/LectureExample_target.cpp&lt;/tt&gt;'],['../group__CG__Lesson0.html#autotoc_md128',1,'Example — &lt;tt&gt;student/examples/StudentExample_target.cpp&lt;/tt&gt;'],['../group__CG__Lesson0.html#autotoc_md122',1,'Implementation — &lt;tt&gt;course/src/LectureExample_privateAPI.cpp&lt;/tt&gt;'],['../group__CG__Lesson0.html#autotoc_md127',1,'Implementation — &lt;tt&gt;student/src/StudentExample_privateAPI.cpp&lt;/tt&gt;']]],
  ['cpp_20tt_20implementation_20files_33',['3.2 &lt;tt&gt;.cpp&lt;/tt&gt; (Implementation Files)',['../group__CG__Lesson0.html#autotoc_md96',1,'']]],
  ['creating_20your_20fork_20required_20for_20students_34',['1.0 Creating Your Fork (Required for Students)',['../group__CG__RepositorySetup.html#autotoc_md8',1,'']]]
];
